name = "image-bed"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "hyeriphotos"

[vars]
R2_CUSTOM_DOMAIN = "https://hyeriphotos.hyeri.us.kg"
PASSWORD = "056450"
BACKGROUND_IMAGE = "https://images.yourdomain.com/background.jpg"
